# Generated by Django 5.0.6 on 2024-05-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='foo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
